heat_template_version: 2014-10-16

description: >
  Floating IP
resources:
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: floatingip_network_name }

parameters:
  floatingip_network_name:
    type: string

outputs:
  floating_ip_id:
    value: { get_resource: floating_ip }
  floating_ip_address:
    value: { get_attr: [ floating_ip, floating_ip_address ] }
