heat_template_version: 2015-10-15

description: Stack de deploiement du volume os

parameters:
  image:
    type: string
    label: The debian based for instance
    description: image=debian-8-latest
    default: debian-8-latest
    constraints:
      - {custom_constraint: glance.image}
  vol_size:
    type: number
    description: The size of the Cinder volume for instance
    default: 5
  vol_type:
    type: string
    description: The volume type of the Cinder volume for instance
    default: default
    constraints:
      - {custom_constraint: cinder.vtype}

resources:
  os_vol:
    type: OS::Cinder::Volume
    properties:
      name: { get_param: image }
      size: { get_param: vol_size }
      image: { get_param: image }
      volume_type: { get_param: vol_type }

outputs:
  os_vol_id:
    value: { get_resource: os_vol }
  os_vol_name:
    value: { get_param: image }
