PROJECT_ID="a81de89a17994b0eaf028767975c0aa8"
LOGS_CONTAINER="swarm-logs"
LOGS_READ_ACL="$PROJECT_ID:*"
LOGS_WRITE_ACL="$PROJECT_ID:*"

DATA_CONTAINER="swarm-data"
DATA_READ_ACL="$PROJECT_ID:*"
DATA_WRITE_ACL="$PROJECT_ID:*"

IMAGES_CONTAINER="swarm-docker-images"
IMAGES_READ_ACL=".r:*,.rlistings"
IMAGES_WRITE_ACL="$PROJECT_ID:*"

INFRA_CONTAINER="swarm-infra"
INFRA_READ_ACL=".r:*,.rlistings"
INFRA_WRITE_ACL="$PROJECT_ID:*"

COMMON_CONTAINER="swarm-common"
COMMON_READ_ACL=".r:*,.rlistings"
COMMON_WRITE_ACL="$PROJECT_ID:*"

PLATEFORME_CONTAINER="swarm-plateforme"
PLATEFORME_READ_ACL=".r:*,.rlistings"
PLATEFORME_WRITE_ACL="$PROJECT_ID:*"

PLATEFORME_DEV_CONTAINER="swarm-plateforme-dev"
PLATEFORME_DEV_READ_ACL=".r:*,.rlistings"
PLATEFORME_DEV_WRITE_ACL="$PROJECT_ID:*"

PLATEFORME_PROD_CONTAINER="swarm-plateforme-prod"
PLATEFORME_PROD_READ_ACL=".r:*,.rlistings"
PLATEFORME_PROD_WRITE_ACL="$PROJECT_ID:*"


