version: '3.4'

services:

  reverse-proxy:
    image: privateregistry/traefik:1.7
    command:
      - "--api"
      - "--accessLog"
      - "--loglevel=INFO"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.watch"
      - "--entrypoints=Name:http Address::80 Compress:true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    networks:
      - traefik-frontend
      - portainer_agent_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.leader!=true
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-frontend"
        - "traefik.redirectorservice.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:traefik"
        - "traefik.frontend.rule=PathPrefixStrip: /traefik"

networks:
  traefik-frontend:
    external: true
    name: traefik-frontend
  portainer_agent_network:
    external: true
